// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SortableCardsController from "./sortable_cards_controller"
application.register("sortable-cards", SortableCardsController)

import SortableRowsController from "./sortable_rows_controller"
application.register("sortable-rows", SortableRowsController)

import TagFormController from "./tag_form_controller"
application.register("tag-form", TagFormController)
